// flow-typed signature: a505f5b89825cb4ac9325c8374e3b218
// flow-typed version: <<STUB>>/snuownd_v^1.1.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'snuownd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'snuownd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'snuownd/snuownd' {
  declare module.exports: any;
}

declare module 'snuownd/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'snuownd/snuownd.js' {
  declare module.exports: $Exports<'snuownd/snuownd'>;
}
declare module 'snuownd/test.js' {
  declare module.exports: $Exports<'snuownd/test'>;
}
